name: les_ailes
description: Les ailes

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.59+59
environment:
  sdk: ">=2.17.1"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  another_flushbar: ^1.10.29
  auto_route: ^9.3.0+1
  cached_network_image: ^3.2.0
  captcha_solver: ^1.0.4
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.2
  cupertino_icons: ^1.0.2
  dart_date: ^1.1.1
  easy_localization: ^3.0.0
  extended_nested_scroll_view: ^6.0.0
  firebase_core: ^3.10.0
  firebase_dynamic_links: ^6.1.0
  firebase_messaging: ^15.2.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.7.0
  flutter_hooks: ^0.20.5
  flutter_html: ^3.0.0-alpha.5
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^2.0.9
  flutter_switch: ^0.3.2
  font_awesome_flutter: ^10.5.0
  form_builder_validators: ^11.1.1
  geolocator: ^13.0.2
  get_it: ^8.0.3
  hashids2: ^2.0.0
  hex: ^0.2.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  launch_review: ^3.0.1
  location: ^7.0.1
  map_launcher: ^3.5.0
  maps_launcher: ^3.0.0+1
  mask_text_input_formatter: ^2.5.0
  modal_bottom_sheet: ^3.0.0
  nfc_manager: ^3.4.0
  niku: ^2.4.3
  otp_autofill: ^4.1.0
  package_info_plus: ^8.0.0
  pin_code_fields: ^8.0.1
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.1
  scrolls_to_top: ^2.1.1
  shimmer: ^3.0.0
  sms_autofill: ^2.2.0
  sticky_headers: ^0.3.0+2
  timer_count_down: ^2.2.1
  url_launcher: ^6.0.20
  vertical_scrollable_tabview: ^0.1.1
  yandex_mapkit: ^4.1.0

dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  analyzer: ^6.11.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  source_gen: null

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - resources/langs/
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  fonts:
    - family: ProximaSoft
      fonts:
        - asset: fonts/ProximaSoft-Regular.ttf
    # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
